---
title: "599_Project1"
author: "Corey"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(skimr)
library(survival)# a change
library(survminer)
library(reReg)
library(KMsurv)
library(Ecdat)
```
This is a study of Natural vs Anthropogenic soils for 

```{r}
#data repo: https://github.com/bobbyjy/MyData

#load dataset into git repo
thePath="https://raw.githubusercontent.com/bobbyjy/MyData/main/"

#update with file name for project 1
Anth=read_csv(paste(thePath,"Anthropogenic.csv",sep="/"))

#load dataset into git repo
thePath="https://raw.githubusercontent.com/bobbyjy/MyData/main/"

#update with file name for project 1
Nat=read_csv(paste(thePath,"Natural.csv",sep="/"))

Anth<-Anth %>% mutate(anthro=1)
Nat<-Nat %>% mutate(anthro=0)
coraldf <- combine(Anth,Nat)

```
```{r}
#comparing temperature and survival
Temp <- coraldf %>% select(Temperature, Time, Status)
km.Temp =survfit(Surv(Temp$Time,Temp$Status)~Temp$Temperature)

p <- ggsurvplot(fit=km.Temp, data=Temp,
           legend = "bottom", risk.table = F,conf.int=F, legend.title = "Study Temperatures: ") +
    labs(
        title="Visualizing the Impact of Global Warming on Coral Populations",
        subtitle = "Observing Coral Survival in 26C and 30C Groups",
        x="Time Until Coral Death (Weeks)"
    ) 

p$plot + scale_colour_manual(values = c("turquoise1", "red"))+
  theme(panel.background = element_rect(fill = "grey12"),
        plot.background = element_rect(fill="grey12"),
        axis.text.x=element_text(colour="white"),
        axis.text.y=element_text(colour="white"),
        plot.title = element_text(colour = "white"),
        axis.title.x = element_text(colour = "white"),
        axis.title.y = element_text(colour = "white"),
        axis.line.x = element_line(color="white"),
        axis.line.y = element_line(color="white"),
        legend.key = element_rect(fill = "grey12"),
        legend.background = element_rect(fill="grey12"),
        legend.text = element_text(color = "white"),
        legend.title = element_text(color = "white"),
        plot.subtitle = element_text(color="white"))+
   annotate("text", x = 2, y = .25, label = "30C Group", color = "red", fontface = "bold")+
  annotate("text", x = 6, y = .65, label = "26C Group", color = "turquoise1", fontface = "bold")

#add annotation labels for the temp groups
#fix legend background
# setwd("C:\\Users\\corey\\OneDrive\\Documents\\GitHub\\599_Project1")
# ggsave("GlobalWarmingImpact.png", dpi = 300)

survdiff(Surv(Temp$Time,Temp$Status)~Temp$Temperature)
```

```{r}
#compare between Nat at different sediment levels 
Nat30 <- Nat %>% filter(Temperature ==30)
km.Nat30 =survfit(Surv(Nat30$Time,Nat30$Status)~Nat30$Sediment)

p2 <- ggsurvplot(fit=km.Nat30, data=Nat30,
           legend = "bottom", risk.table = F,conf.int=F, legend.title = "Study Sediment Levels", alpha=.5) +
    labs(
        title="Survival Using Natural Sediments at 4 Levels",
        subtitle = "No Significant Difference Observed",
        x="Time Until Death"
    ) 

p2$plot+  scale_colour_manual(values = c("turquoise1", "magenta","green","yellow"))+
  #scale_color_brewer(palette = "Accent")+
  theme(panel.background = element_rect(fill = "grey12"),
        plot.background = element_rect(fill="grey12"),
        axis.text.x=element_text(colour="white"),
        axis.text.y=element_text(colour="white"),
        plot.title = element_text(colour = "white"),
        axis.title.x = element_text(colour = "white"),
        axis.title.y = element_text(colour = "white"),
        axis.line.x = element_line(color="white"),
        axis.line.y = element_line(color="white"),
        legend.key = element_rect(fill = "grey12"),
        legend.background = element_rect(fill="grey12"),
        legend.text = element_text(color = "white"),
        legend.title = element_text(color = "white"),
        plot.subtitle = element_text(color="white"))

# setwd("C:\\Users\\corey\\OneDrive\\Documents\\GitHub\\599_Project1")
# ggsave("NaturalSedimentLevels.png", dpi = 300)
survdiff(Surv(Nat30$Time,Nat30$Status)~Nat30$Sediment)
```
```{r}
#compare between Anth at different sediment levels 
# Anth30 <- Anth %>% filter(Temperature ==30)
# km.Anth30 =survfit(Surv(Anth30$Time,Anth30$Status)~Anth30$Sediment)
# 
# ggsurvplot(fit=km.Anth30, data=Anth30,
#            legend = "bottom", risk.table = F,conf.int=F,linetype = "strata", legend.title = "Study Sediment Levels") +
#     labs(
#         title="Survival Using Anthropgenic Sediments at 4 Levels",
#         x="Time Until Death"
#     ) 
```
```{r}
#compare between Anth and Nat at 30 degrees
Both30 <- coraldf %>% filter(Temperature ==30)
km.Both30 =survfit(Surv(Both30$Time,Both30$Status)~Both30$anthro)

p3 <- ggsurvplot(fit=km.Both30, data=Both30,
           legend = "bottom", risk.table = F,conf.int=F, legend.title = "Anth or Nat", surv.median.line = "v") +
    labs(
        title="Anthro vs. Natural at Predicted Global Warming Temp (30C)",
        x="Time Until Death"
    ) 

p3$plot+ scale_colour_manual(values = c("green", "grey70"))+
  theme(panel.background = element_rect(fill = "grey12"),
        plot.background = element_rect(fill="grey12"),
        axis.text.x=element_text(colour="white"),
        axis.text.y=element_text(colour="white"),
        plot.title = element_text(colour = "white"),
        axis.title.x = element_text(colour = "white"),
        axis.title.y = element_text(colour = "white"),
        axis.line.x = element_line(color="white"),
        axis.line.y = element_line(color="white"),
        legend.key = element_rect(fill = "grey12"),
        legend.background = element_rect(fill="grey12"),
        legend.text = element_text(color = "white"),
        legend.title = element_text(color = "white"),
        plot.subtitle = element_text(color="white"),
        legend.position = "")+
   annotate("text", x = 1, y = .15, label = "Artificial (30C)", color = "grey70", fontface = "bold")+
  annotate("text", x = 6, y = .4, label = "Natural (30C)", color = "green", fontface = "bold")

# setwd("C:\\Users\\corey\\OneDrive\\Documents\\GitHub\\599_Project1")
# ggsave("NaturalvsAnthro.png", dpi = 300)

survdiff(Surv(Both30$Time,Both30$Status)~Both30$anthro)
```

```{r}
#compare between Anth and Nat at 26 degrees
Both26 <- coraldf %>% filter(Temperature ==26)
km.Both26 =survfit(Surv(Both26$Time,Both26$Status)~Both26$anthro)

p4 <- ggsurvplot(fit=km.Both26, data=Both26,
           legend = "bottom", risk.table = F,conf.int=F, legend.title = "Anth or Nat", surv.median.line = "v") +
    labs(
        title="Anthro vs. Natural at Low Temp (26C)",
        x="Time Until Death"
    ) 

p4$plot + scale_colour_manual(values = c("green", "grey70"))+
  theme(panel.background = element_rect(fill = "grey12"),
        plot.background = element_rect(fill="grey12"),
        axis.text.x=element_text(colour="white"),
        axis.text.y=element_text(colour="white"),
        plot.title = element_text(colour = "white"),
        axis.title.x = element_text(colour = "white"),
        axis.title.y = element_text(colour = "white"),
        axis.line.x = element_line(color="white"),
        axis.line.y = element_line(color="white"),
        legend.key = element_rect(fill = "grey12"),
        legend.background = element_rect(fill="grey12"),
        legend.text = element_text(color = "white"),
        legend.title = element_text(color = "white"),
        plot.subtitle = element_text(color="white"),
        legend.position = "")+
   annotate("text", x = 2, y = .4, label = "Artificial (26C)", color = "grey70", fontface = "bold")+
  annotate("text", x = 6, y = .6, label = "Natural (26C)", color = "green", fontface = "bold")

# setwd("C:\\Users\\corey\\OneDrive\\Documents\\GitHub\\599_Project1")
# ggsave("NaturalvsAnthroLowTemp.png", dpi = 300)

survdiff(Surv(Both26$Time,Both26$Status)~Both26$anthro)
```



```{r}
#comparing temperature and
Anth <- Anth %>% mutate(anthro=1)
Nat <- Nat %>% mutate(anthro=0)
coraldf <- combine(Anth,Nat)
coraldf

#groups are the sediment
#sediment values for sed valyues
Anth
km.censoring =survfit(Surv(Anth$Time,Anth$Status)~1)


ggsurvplot(fit=km.censoring, data=Anth,
           legend = "bottom", risk.table = F,conf.int=F,linetype = "strata") +
    labs(
        title="Survival Curve for Pharmaco Study",
        x="Time to Relapse)"
    ) 


Nat
km.censoring =survfit(Surv(Nat$Time,Nat$Status)~1)


km.strata=survfit(Surv(coraldf$Time,coraldf$Status)~coraldf$anthro + strata(coraldf$Sediment)) #defines your strata!

ggsurvplot(fit=km.strata, data=coraldf,
           legend = "bottom", risk.table = F,conf.int=F,linetype = "strata") +
    labs(
        title="Survival Curve for Pharmaco Study",
        x="Time to Relapse)"
    ) 

km.strata=survfit(Surv(coraldf$Time,coraldf$Status)~coraldf$anthro) #defines your strata!

ggsurvplot(fit=km.strata, data=coraldf,
           legend = "bottom", risk.table = F,conf.int=F,linetype = "strata") +
    labs(
        title="Survival Curve for Pharmaco Study",
        x="Time to Relapse)"
    ) 

survdiff(Surv(coraldf$Time,coraldf$Status)~coraldf$anthro + strata(coraldf$Sediment))


survdiff(Surv(coraldf$Time,coraldf$Status)~coraldf$anthro)


```
```{r}

km.strata=survfit(Surv(coraldf$Time,coraldf$Status)~coraldf$Sediment) #defines your strata!

ggsurvplot(fit=km.strata, data=coraldf,
           legend = "bottom", risk.table = F,conf.int=F, legend.title = "Sediment Concentration",) +
    labs(
        title="Survival Curve for Pharmaco Study",
        x="Weeks to Coral Death"
    ) 

survdiff(Surv(coraldf$Time,coraldf$Status)~coraldf$Sediment)

```

```{r}
#sample_n(ds,25) to take a random 25 samples from your data set

#Lollipop chart Example:
sample_ds %>%
  ggplot()+
  geom_segment(aes(x=0,y=fct_reorder(studentID, SATmin,.desc=TRUE), xend=SATmin, yend=fct_reorder(studentID, SATmin,.desc=TRUE)), color = "blue2", show.legend = FALSE)+
  geom_point(aes(x = SATmin, y = studentID, alpha = SATmin), size = 4, color = "blue2", show.legend = FALSE)+
  CoreyPlotTheme+
  labs(y = "Student ID", x = "Time (mins)", title = "Sample Student SAT Times")
 
```

```{r}
#some summary stats
ds %>% 
  summarise(mean=mean(sec_hours), min = min(sec_hours), quant25 = quantile(sec_hours, .25), median = quantile(sec_hours, .5), quant75 = quantile(sec_hours, .75), quant90 = quantile(sec_hours, .9), max = max(sec_hours), studentcount =n())
```

```{r}
#without censoring
km.nocensoring=survfit(Surv(scds1$time,rep(1,nrow(scds1)))~1)

#with censoring
km.censoring =survfit(Surv(scds1$time,scds1$status)~1)
summary(km.censoring)

#with groups
km = survfit(Surv(rats2.2$timeElapsed,rats2.2$status)~rats2.2$trt)

#with strata
ggsurvplot(fit=km.strata, data=ds,
           legend = "bottom", risk.table = F,conf.int=F,linetype = "strata") +
    labs(
        title="Survival Curve for Pharmaco Study",
        x="Time to Relapse)"
    ) 

#hypothesis test
survdiff(Surv(ds$ttr,ds$relapse)~ds$grp + strata(ds$ageGroup2))
```
```{r}

coraldf$Sediment<-as.factor(coraldf$Sediment)
coraldf$Temperature<-as.factor(coraldf$Temperature)



coraldf %>%
    group_by(Sediment, anthro, Temperature)%>%summarise(Time=mean(Time))%>%
    ggplot()+
    geom_bar(aes(x=Time,y=Sediment),stat='identity',
                 color = "blue2",width=.01)+
    geom_point(aes(x = Time, y = Sediment,size = -as.numeric(Sediment)), show.legend = FALSE,color='blue2')+
    facet_grid(anthro~Temperature)
  CoreyPlotTheme+
    labs(y = "Sediment", x = "Time", title = "Coral survival time")
  
  ```






